calibration:
  shoulder_pan:
    min_ticks: 500
    center_ticks: 2048
    max_ticks: 3596
  shoulder_lift:
    min_ticks: 500
    center_ticks: 2048
    max_ticks: 3596
  elbow_flex:
    min_ticks: 500
    center_ticks: 2048
    max_ticks: 3596
  wrist_flex:
    min_ticks: 500
    center_ticks: 2048
    max_ticks: 3596
  wrist_roll:
    min_ticks: 0
    center_ticks: 2048
    max_ticks: 4095
  gripper:
    min_ticks: 1500
    center_ticks: 2048
    max_ticks: 2596